{"name": "Проверка принятия заказа курьером с неверным номером заказа", "status": "passed", "description": "Код операции:404, ответ:\"Заказа с таким id не существует\"", "start": 1729850895380, "stop": 1729850896417, "uuid": "768fc996-2ba9-4ddf-92a9-201cb651c954", "historyId": "19c3f04cb780369a783728905441cd9d", "testCaseId": "19c3f04cb780369a783728905441cd9d", "fullName": "tests.order.test_take_order.TestTakeOrders#test_takin_order_wrong_track_id_negative", "labels": [{"name": "parentSuite", "value": "tests.order"}, {"name": "suite", "value": "test_take_order"}, {"name": "subSuite", "value": "TestTakeOrders"}, {"name": "host", "value": "DESKTOP-03BV0KK"}, {"name": "thread", "value": "7868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.order.test_take_order"}]}